app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('rohit/',rohit,name='rohit'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('virat/',virat,name='virat'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.


def rohit(request):
    return render(request,'rohit.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def virat(request):
    return render(request,'virat.html')

templates/rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is rohit html page</h1>
        <h1>this page belongs to app1</h1>
        <a href="{% url 'app2:virat' %}">Go Virat Page</a>
    </center>
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is virat html page</h1>
        <h1>this page belongs to app2</h1>

        <a href="{% url 'app1:rohit' %}">Go rohit Page</a>
    </center>
</body>
</html>